"""add is_new_listing to crawl_session_ads

Revision ID: bb67b9f73556
Revises: 3f7911512915
Create Date: 2026-03-23 01:15:08.175424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb67b9f73556'
down_revision: Union[str, Sequence[str], None] = '3f7911512915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('crawl_session_ads')]
    if 'is_new_listing' not in columns:
        op.add_column('crawl_session_ads', sa.Column('is_new_listing', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_session_ads', 'is_new_listing')
    # ### end Alembic commands ###
