"""add multi-bike model tables

Revision ID: e845082592c4
Revises: bb67b9f73556
Create Date: 2026-03-30 10:33:32.855228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e845082592c4'
down_revision: Union[str, Sequence[str], None] = 'bb67b9f73556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_overrides',
    sa.Column('bike_model_id', sa.Integer(), nullable=False),
    sa.Column('group_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_new_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bike_model_id', 'group_key')
    )
    op.drop_index(op.f('ix_accessory_catalog_variants_group_id'), table_name='accessory_catalog_variants')
    op.drop_table('accessory_catalog_variants')
    op.drop_index(op.f('ix_accessory_catalog_groups_category'), table_name='accessory_catalog_groups')
    op.drop_index(op.f('ix_accessory_catalog_groups_model_id'), table_name='accessory_catalog_groups')
    op.drop_table('accessory_catalog_groups')
    op.alter_column('ads', 'bike_model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ads_bike_model_price'), table_name='ads')
    op.drop_index(op.f('ix_ads_bike_model_variant'), table_name='ads')
    op.drop_column('ads', 'needs_crosscheck')
    op.add_column('crawl_session_ads', sa.Column('is_new_listing', sa.Integer(), nullable=False))
    op.alter_column('crawl_sessions', 'bike_model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_crawl_sessions_bike_model_status'), table_name='crawl_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crawl_sessions_bike_model_status'), 'crawl_sessions', ['bike_model_id', 'status'], unique=False)
    op.alter_column('crawl_sessions', 'bike_model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('crawl_session_ads', 'is_new_listing')
    op.add_column('ads', sa.Column('needs_crosscheck', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_ads_bike_model_variant'), 'ads', ['bike_model_id', 'variant'], unique=False)
    op.create_index(op.f('ix_ads_bike_model_price'), 'ads', ['bike_model_id', 'price'], unique=False)
    op.alter_column('ads', 'bike_model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('accessory_catalog_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expressions', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('default_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_match_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('accessory_catalog_groups_pkey')),
    sa.UniqueConstraint('group_key', name=op.f('accessory_catalog_groups_group_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accessory_catalog_groups_model_id'), 'accessory_catalog_groups', ['model_id'], unique=False)
    op.create_index(op.f('ix_accessory_catalog_groups_category'), 'accessory_catalog_groups', ['category'], unique=False)
    op.create_table('accessory_catalog_variants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qualifiers', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('brands', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('product_aliases', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('optional_words', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('regex_override', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_new_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order_manual', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['accessory_catalog_groups.id'], name=op.f('accessory_catalog_variants_group_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accessory_catalog_variants_pkey')),
    sa.UniqueConstraint('group_id', 'name', name=op.f('accessory_catalog_variants_group_id_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_accessory_catalog_variants_group_id'), 'accessory_catalog_variants', ['group_id'], unique=False)
    op.drop_table('accessory_overrides')
    # ### end Alembic commands ###
