"""add search config extended fields

Revision ID: f63e6aae6ff8
Revises: 0001
Create Date: 2026-03-31 20:01:08.831694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f63e6aae6ff8'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike_search_configs', sa.Column('locations', sa.JSON(), nullable=True))
    op.add_column('bike_search_configs', sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bike_search_configs', sa.Column('price_min', sa.Integer(), nullable=True))
    op.add_column('bike_search_configs', sa.Column('price_max', sa.Integer(), nullable=True))
    op.add_column('bike_search_configs', sa.Column('sort', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bike_search_configs', sa.Column('search_in_title_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike_search_configs', 'search_in_title_only')
    op.drop_column('bike_search_configs', 'sort')
    op.drop_column('bike_search_configs', 'price_max')
    op.drop_column('bike_search_configs', 'price_min')
    op.drop_column('bike_search_configs', 'owner_type')
    op.drop_column('bike_search_configs', 'locations')
    # ### end Alembic commands ###
